project_id = "hyiyuhjabjnksjbqfwmn"

[functions.generate-story]
verify_jwt = true

[functions.refresh-entitlements]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.revenuecat-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false