// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyiyuhjabjnksjbqfwmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5aXl1aGphYmpua3NqYnFmd21uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI0NTU1NjEsImV4cCI6MjA0ODAzMTU2MX0.hE2rTn4kMe34WfKgiizQQ9t1MLWVQuKJt-7r8v2M3ZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);